//
// Created by wsoll on 4/11/2026.
//
#include "core/EngineContext.hpp"
#include "app/AppConfig.hpp"
#include "renderer/VulkanRenderer.hpp"
#include "core/BufferManager.hpp"

namespace ndde {

    EngineContext::EngineContext() {
        // 1. Initialize Configuration first (The "Source of Truth")
        config = std::make_unique<AppConfig>();

        // 2. Initialize the Renderer
        // We pass the config to the renderer so it knows the 2D/3D state
        renderer = std::make_unique<VulkanRenderer>(*config);

        // 3. Initialize the Buffer Manager
        // This will handle the "Physicality" of the vertices generated by ICurve
        buffers = std::make_unique<BufferManager>();
    }

    EngineContext::~EngineContext() {
        /**
         * The order of destruction is critical in Vulkan.
         * We must destroy the buffers and renderer before
         * the underlying Vulkan Instance/Device is lost.
         */
        buffers.reset();
        renderer.reset();
        config.reset();
    }

} // namespace ndde