#!/usr/bin/env python3
"""
clean_explorer.py
-----------------
Deletes all .explorer/ build artifact directories in the repo.
Safe to run at any time — everything is regenerated by run_extraction.py.

Usage (from the repo root):
    python theorem-explorer/clean_explorer.py
"""

import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

def main() -> None:
    found = list(REPO_ROOT.rglob(".explorer"))
    if not found:
        print("No .explorer directories found.")
        return
    for d in found:
        if d.is_dir():
            shutil.rmtree(d)
            print(f"Deleted: {d.relative_to(REPO_ROOT)}")
    print(f"\nDone. Removed {len(found)} .explorer director{'y' if len(found)==1 else 'ies'}.")
    print("Run  python theorem-explorer/run_extraction.py  to rebuild.")

if __name__ == "__main__":
    main()
